# Generated by Django 3.2.9 on 2021-12-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10)),
                ('dataindex', models.IntegerField(max_length=5)),
                ('data', models.TextField()),
            ],
        ),
    ]
