# Generated by Django 3.2.9 on 2021-12-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonfilter',
            name='dataindex',
            field=models.IntegerField(),
        ),
    ]
