# Generated by Django 3.2.9 on 2021-12-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0002_alter_seasonfilter_dataindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataindex', models.IntegerField()),
                ('club', models.TextField()),
                ('win', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
    ]
