# Generated by Django 3.2.9 on 2021-12-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportApp', '0003_seasonwin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataindex', models.IntegerField()),
                ('club', models.TextField()),
                ('goal', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SeasonShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataindex', models.IntegerField()),
                ('club', models.TextField()),
                ('shots', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
            ],
        ),
    ]
